name: Generate Route-Based Mocks & Mockoon Export

on:
  push:
    paths:
      - 'swagger.json'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'

jobs:
  build-mocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Generate route-based JSON files
        run: npm run generate-mocks

      - name: Generate Mockoon export
        run: npm run mockoon-export

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mockoon-mocks
          path: |
            mocks/
            mockoon-export.json