name: Generate Route-Based Mocks & Mockoon Export

on:
  push:
    paths:
      - 'swagger.json'
      - 'scripts/**'
      - 'package.json'
      - 'package-lock.json'

permissions:
  contents: write

jobs:
  build-mocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        env:
          NODE_ENV: development
        run: npm ci

      - name: Check if swagger.json changed
        id: check_diff
        run: |
          git fetch origin
          if git diff --quiet origin/HEAD -- swagger.json; then
            echo "Swagger did not change."
            echo "continue=false" >> $GITHUB_OUTPUT
          else
            echo "Swagger changed."
            echo "continue=true" >> $GITHUB_OUTPUT
          fi

      - name: Generate route-based JSON files
        if: steps.check_diff.outputs.continue == 'true'
        run: npm run generate

      - name: Commit generated mocks
        if: steps.check_diff.outputs.continue == 'true'
        uses: EndBug/add-and-commit@v9
        with:
          author_name: 'github-actions'
          author_email: 'actions@github.com'
          message: 'chore: update generated mocks and Mockoon export'
          add: |
            mocks/
            mockoon-export.json